export const ADD_ARTICLE = "ADD_ARTICLE";
export const REMOVE_ARTICLE = "REMOVE_ARTICLE";
export const GET_ARTICLE = "GET_ARTICLE";
export const GET_ARTICLE_SUCCEEDED = "GET_ARTICLE_SUCCEEDED";
export const GET_ARTICLE_FAILED = "GET_ARTICLE_FAILED";
